service: fs
type: counters
keys:
  - device
  - mountPoint
ignore-fields:
  - usedSize
  - availSize
show-fields:
  - device
  - totalSize
  - usedSize
  - usedPercent
  - mountPoint
apply:
  cumulus:
    copy: linux

  linux:
    version: all
    command: df -hT
    textfsm: textfsm_templates/fs.tfsm

  eos:
    version: all
    command: bash timeout 5 df -hT
    textfsm: textfsm_templates/fs.tfsm
    
  nxos:
    version: all
    command: run bash df -hT
    textfsm: textfsm_templates/fs.tfsm
